version: 2
updates:
- package-ecosystem: composer
  directory: "/api"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  versioning-strategy: increase
- package-ecosystem: package.json
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  versioning-strategy: increase
